#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_home:
   path: /
   controller: App\Controller\HomeController::index
app_register:
   path: /inscription
   controller: App\Controller\RegisterController::index
app_login:
   path: /connexion
   controller: App\Controller\SecurityController::login
app_account:
   path: /compte
   controller: App\Controller\AccountController::index
